### ISSUE TITLE
Old map texture, as a background

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/eurostat-map#30]
Try to add a map background to give an old map style, with some transparency for the foreground.
Example:
https://github.com/eurostat/eurostat-map.js/blob/dev/docs/img/test_old.png
with
https://www.myfreetextures.com/wp-content/uploads/2014/11/old-brown-paper-texture-image.jpg

**Comment by joewdavies** [comment]
For the sake of simplicity, I think this is something that the developers could do themselves with a bit of javascript/css and shouldn't be seen as part of the core map-making engine
