### ISSUE TITLE
Several statistics maps

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/eurostat-map#33]
In order to be able to make maps based on several statistics, it is necessary to make it possible to load not only one but several statistical sources.

Examples of such maps:
- proportionnal circles colored depending on evolution rate
- value-by-alpha maps. See http://andywoodruff.com/blog/how-to-make-a-value-by-alpha-map/
- or more generally, bi/multi-variate maps. See https://gistbok.ucgis.org/bok-topics/multivariate-mapping
- maps showing one stat indicator computed on-th-fly as an aggregation of several stat variables
- See all examples in: https://minds.wisconsin.edu/handle/1793/67887
- ...

**Comment by joewdavies** [comment]
Bivariate choropleths and proportional symbols are currently possible so i'm closing in order to clean up issues!
