### ISSUE TITLE
proportionnal symbols: Use perceptual scaling

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/eurostat-map#37]
The area of the symbols should not be exactly proportionnal to its value. The 'perceived area' should be used instead.
See: https://makingmaps.net/2007/08/28/perceptual-scaling-of-map-symbols/

**Comment by joewdavies** [comment]
Note: it seems this technique should only be applied to circles:
> perceptual scaling should only be applied to circles. If the symbol is changed in ArcGIS, to a square or some other shape, the perceptual scaling can still be applied. Research has shown that square symbols, on a proportional symbol map, don’t have the same perceptual problem that circles do (we can correctly estimate the areas of squares

At the moment, the user can provide their own scaling function: see psSizeFun in https://github.com/eurostat/eurostat-map/blob/master/docs/reference.md#proportional-symbol-map

> The D3 scale function used to define the sizes of the symbols. The following methods are then called internally: psSizeFun().domain(sizeDomain).range([psMinSize, psMaxSize])

The default is d3.scaleSqrt so in fact, absolute scaling isnt used by default. I suppose the question is: Do we apply scaleSqrt to circles and scaleLinear to everything else? or keep everything as it is?

Closing for now, feel free to reopen if any other changes might be necessary regarding this!
